spring:
  application:
    name: ldy-ai-code-mother
server:
  port: 8123
  servlet:
    context-path: /api
springdoc:
  group-configs:
    - group: 'default'
      packages-to-scan: com.ldy.ldyaicodemother.controller
knife4j:
  enable: true
  setting:
    language: zh_cn
